services:
   sonata.admin.admin.auditoria:
      class: SIGESRHI\AdminBundle\Admin\AuditoriaAdmin
      tags:
        - { name: sonata.admin, manager_type: orm, group: Configuraciones de permisos, label: Auditoria}
      arguments: [null, SIGESRHI\AdminBundle\Entity\Auditoria, AdminBundle:AuditoriaAdmin]

   sonata.admin.admin.modulo:
      class: SIGESRHI\AdminBundle\Admin\ModuloAdmin
      tags:
        - { name: sonata.admin, manager_type: orm, group: Configuraciones de permisos, label: Módulos }
      arguments: [null, SIGESRHI\AdminBundle\Entity\Modulo, AdminBundle:ModuloAdmin]

   sonata.admin.admin.acceso:
      class: SIGESRHI\AdminBundle\Admin\AccesoAdmin
      tags:
        - { name: sonata.admin, manager_type: orm, group: Configuraciones de permisos, label: Accesos }
      arguments: [null, SIGESRHI\AdminBundle\Entity\Acceso, AdminBundle:AccesoAdmin]

   sonata.admin.admin.centro:
      class: SIGESRHI\AdminBundle\Admin\CentroAdmin
      tags:
        - { name: sonata.admin, manager_type: orm, group: Institución, label: Centros de atención }
      arguments: [null, SIGESRHI\AdminBundle\Entity\Centrounidad, AdminBundle:CentroAdmin]

   sonata.admin.admin.unidad:
      class: SIGESRHI\AdminBundle\Admin\UnidadAdmin
      tags:
        - { name: sonata.admin, manager_type: orm, group: Institución, label: Unidad Organizativa }
      arguments: [null, SIGESRHI\AdminBundle\Entity\Unidadorganizativa, AdminBundle:UnidadAdmin]

   sonata.admin.admin.plaza:
      class: SIGESRHI\AdminBundle\Admin\PlazaAdmin
      tags:
        - { name: sonata.admin, manager_type: orm, group: Manual de puestos, label: Administrar Plazas }
      arguments: [null, SIGESRHI\AdminBundle\Entity\Plaza, AdminBundle:PlazaAdmin]

   sonata.admin.admin.resultados:
      class: SIGESRHI\AdminBundle\Admin\ResultadosAdmin
      tags:
        - { name: sonata.admin, manager_type: orm, group: Manual de puestos, label: Resultados, show_in_dashboard: false }
      arguments: [null, SIGESRHI\AdminBundle\Entity\Resultados, AdminBundle:ResultadosAdmin]

   sonata.admin.admin.conocimiento:
      class: SIGESRHI\AdminBundle\Admin\ConocimientoAdmin
      tags:
        - { name: sonata.admin, manager_type: orm, group: Manual de puestos, label: Conocimientos, show_in_dashboard: false }
      arguments: [null, SIGESRHI\AdminBundle\Entity\Conocimiento, AdminBundle:ConocimientoAdmin]

   sonata.admin.admin.competencia:
      class: SIGESRHI\AdminBundle\Admin\CompetenciaAdmin
      tags:
        - { name: sonata.admin, manager_type: orm, group: Manual de puestos, label: Competencias, show_in_dashboard: false }
      arguments: [null, SIGESRHI\AdminBundle\Entity\Competencia, AdminBundle:CompetenciaAdmin]

   sonata.admin.admin.funcion:
      class: SIGESRHI\AdminBundle\Admin\FuncionAdmin
      tags:
        - { name: sonata.admin, manager_type: orm, group: Manual de puestos, label: Funciones, show_in_dashboard: false }
      arguments: [null, SIGESRHI\AdminBundle\Entity\Funcion, AdminBundle:FuncionAdmin]

   sonata.admin.admin.marcoref:
      class: SIGESRHI\AdminBundle\Admin\MarcoreferenciaAdmin
      tags:
        - { name: sonata.admin, manager_type: orm, group: Manual de puestos, label: Marco de referencia, show_in_dashboard: false }
      arguments: [null, SIGESRHI\AdminBundle\Entity\Marcoreferencia, AdminBundle:MarcoreferenciaAdmin]

   sonata.admin.admin.titulo:
      class: SIGESRHI\AdminBundle\Admin\TituloAdmin
      tags:
        - { name: sonata.admin, manager_type: orm, group: Manual de puestos, label: Titulo, show_in_dashboard: false}
      arguments: [null, SIGESRHI\ExpedienteBundle\Entity\Titulo, AdminBundle:TituloAdmin]

   sonata.admin.admin.telefono:
      class: SIGESRHI\AdminBundle\Admin\TelefonoAdmin
      tags:
        - { name: sonata.admin, manager_type: orm, group: Institución, label: Teléfonos, show_in_dashboard: false}
      arguments: [null, SIGESRHI\AdminBundle\Entity\Telefono, AdminBundle:TelefonoAdmin]

   sonata.admin.admin.tipoaccion:
      class: SIGESRHI\AdminBundle\Admin\TipoaccionAdmin
      tags:
        - { name: sonata.admin, manager_type: orm, group: Institución, label: Tipos de acciones de personal}
      arguments: [null, SIGESRHI\ExpedienteBundle\Entity\Tipoaccion, AdminBundle:TipoaccionAdmin]

   sonata.admin.admin.tituloplaza:
      class: SIGESRHI\AdminBundle\Admin\TituloplazaAdmin
      tags:
        - { name: sonata.admin, manager_type: orm, group: Manual de puestos, label: Titulo plaza, show_in_dashboard: false}
      arguments: [null, SIGESRHI\AdminBundle\Entity\Tituloplaza, AdminBundle:TituloplazaAdmin]

   sonata.admin.admin.otrosidiomas:
      class: SIGESRHI\AdminBundle\Admin\OtrosidiomasAdmin
      tags:
        - { name: sonata.admin, manager_type: orm, group: Manual de puestos, label: Otros idiomas, show_in_dashboard: false}
      arguments: [null, SIGESRHI\AdminBundle\Entity\Otrosidiomas, AdminBundle:OtrosidiomasAdmin]

   sonata.admin.admin.idiomasplaza:
      class: SIGESRHI\AdminBundle\Admin\IdiomasplazaAdmin
      tags:
        - { name: sonata.admin, manager_type: orm, group: Manual de puestos, label: Idiomas, show_in_dashboard: false}
      arguments: [null, SIGESRHI\AdminBundle\Entity\Idiomasplaza, AdminBundle:IdiomasplazaAdmin]

   sonata.admin.admin.conocimientoplaza:
      class: SIGESRHI\AdminBundle\Admin\ConocimientoplazaAdmin
      tags:
        - { name: sonata.admin, manager_type: orm, group: Manual de puestos, label: Conocimiento plaza, show_in_dashboard: false}
      arguments: [null, SIGESRHI\AdminBundle\Entity\Conocimientoplaza, AdminBundle:ConocimientoplazaAdmin]

   sonata.admin.admin.otrosaspectos:
      class: SIGESRHI\AdminBundle\Admin\OtrosaspectosAdmin
      tags:
        - { name: sonata.admin, manager_type: orm, group: Manual de puestos, label: Otros aspectos, show_in_dashboard: false}
      arguments: [null, SIGESRHI\AdminBundle\Entity\Otrosaspectos, AdminBundle:OtrosaspectosAdmin]
