fos_user_security:
   resource: "@FOSUserBundle/Resources/config/routing/security.xml"
sonata_user_profile:
   resource: "@SonataUserBundle/Resources/config/routing/profile.xml"
   prefix: /profile
fos_user_register:
   resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
   prefix: /register
fos_user_resetting:
   resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
   prefix: /resetting
fos_user_change_password:
   resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
   prefix: /change-password
fos_user_group:
   resource: "@FOSUserBundle/Resources/config/routing/group.xml"
   prefix: /group

sonata_user:
   resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
   prefix: /admin
sonata_user_impersonating:
   pattern: /
   defaults: { _controller: AdminBundle:Default:index }

hello_page:
   path:  /inicio/
   defaults: { _controller: AdminBundle:Default:index }

AdminBundle_plaza:
   resource: "@AdminBundle/Resources/config/routing/plaza.yml"
   prefix:   /plaza

cambia_opcion:
   path: /inicio/{acceso}/{ruta}
   defaults: {_controller: AdminBundle:Default:cambiaopcion}

AdminBundle_pantallas:
   resource: "@AdminBundle/Resources/config/routing/pantallas.yml"
   prefix:   /home   

AdminBundle_refrenda:
   resource: "@AdminBundle/Resources/config/routing/refrenda.yml"
   prefix:   /refrenda

AdminBundle_noticia:
  resource: "@AdminBundle/Resources/config/routing/noticia.yml"
  prefix:   /noticia