parameters:
#    admin.example.class: SIGESRHI\AdminBundle\Example
   security.authentication.success_handler.class: SIGESRHI\AdminBundle\Component\Security\Http\Authentication\AuthenticationSuccessHandler


services:
#    admin.example:
#        class: %admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
   security.authentication.success_handler:
         class: %security.authentication.success_handler.class%
         public: false
         arguments: ['@router', '@security.context']
         tags:
             - { name: kernel.event_listener, event: security.interactive_login }
             - { name: kernel.event_listener, event: kernel.response }
