EvaluacionBundle_evaluacion:
    resource: "@EvaluacionBundle/Resources/config/routing/evaluacion.yml"
    prefix:   /evaluar

EvaluacionBundle_periodoeval:
    resource: "@EvaluacionBundle/Resources/config/routing/periodoeval.yml"
    prefix:   /periodoeval

EvaluacionBundle_incidente:
    resource: "@EvaluacionBundle/Resources/config/routing/incidente.yml"
    prefix:   /incidente

