evaluacion_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: EvaluacionBundle:Default:index }

EvaluacionBundle_evaluacion:
    resource: "@EvaluacionBundle/Resources/config/routing/evaluacion.yml"
    prefix:   /evaluacion

