EvaluacionBundle_evaluacion:
    resource: "@EvaluacionBundle/Resources/config/routing/evaluacion.yml"
    prefix:   /evaluar

EvaluacionBundle_periodoeval:
    resource: "@EvaluacionBundle/Resources/config/routing/periodoeval.yml"
    prefix:   /periodoeval

