EvaluacionBundle_evaluacion:
    resource: "@EvaluacionBundle/Resources/config/routing/evaluacion.yml"
    prefix:   /evaluar

EvaluacionBundle_periodoeval:
    resource: "@EvaluacionBundle/Resources/config/routing/periodoeval.yml"
    prefix:   /periodoeval

EvaluacionBundle_formularioevaluacion:
      resource: "@EvaluacionBundle/Resources/config/routing/formularioevaluacion.yml"
      prefix:   /formularioevaluacion

EvaluacionBundle_factorevaluacion:
      resource: "@EvaluacionBundle/Resources/config/routing/factorevaluacion.yml"
      prefix:   /factorevaluacion

EvaluacionBundle_puntaje:
     resource: "@EvaluacionBundle/Resources/config/routing/puntaje.yml"
     prefix:   /puntaje