parameters:
#    evaluacion.example.class: SIGESRHI\EvaluacionBundle\Example

services:
#    evaluacion.example:
#        class: %evaluacion.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
