<?php

/**
 * This file is part of the <name> project.
 *
 * (c) <yourname> <youremail>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Application\Sonata\UserBundle\Entity;

use FOS\UserBundle\Model\Group as BaseGroup;  


/**
 * This file has been generated by the Sonata EasyExtends bundle ( http://sonata-project.org/bundles/easy-extends )
 *
 * References :
 *   working with object : http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en
 *
 * @author <yourname> <youremail>
 */
class Group extends BaseGroup implements \FOS\UserBundle\Model\GroupInterface
{
    /**
     * @var integer $id
     */
    protected $id;
    protected $idacceso;
    protected $name;
    protected $roles;
       
    public function __construct($name, $roles=array())
    {
        $this->name = $name;
        $this->roles = $roles;
        $this->idacceso = new \Doctrine\Common\Collections\ArrayCollection();
    }

    /**
     * @param string $role
     *
     * @return Group
     */
    public function addRole($role)
    {
        if (!$this->hasRole($role)) {
            $this->roles[] = strtoupper($role);
        }

        return $this;
    }

    public function getId()
    {
        return $this->id;
    }

    public function getName()
    {
        return $this->name;
    }

    /**
     * @param string $role
     */
    public function hasRole($role)
    {
        return in_array(strtoupper($role), $this->roles, true);
    }

    public function getRoles()
    {
        return $this->roles;
    }

    /**
     * @param string $role
     *
     * @return Group
     */
    public function removeRole($role)
    {
        if (false !== $key = array_search(strtoupper($role), $this->roles, true)) {
            unset($this->roles[$key]);
            $this->roles = array_values($this->roles);
        }

        return $this;
    }

    /**
     * @param string $name
     *
     * @return Group
     */
    public function setName($name)
    {
        $this->name = $name;

        return $this;
    }

    /**
     * @param array $roles
     *
     * @return Group
     */
    public function setRoles(array $roles)
    {
        $this->roles = $roles;

        return $this;
    }
    /**
     * Add idacceso
     *
     * @param \SIGESRHI\AdminBundle\Entity\Acceso $idacceso
     * @return Group
     */
    public function addIdacceso(\SIGESRHI\AdminBundle\Entity\Acceso $idacceso)
    {
        $this->idacceso[] = $idacceso;
    
        return $this;
    }

    /**
     * Remove idacceso
     *
     * @param \SIGESRHI\AdminBundle\Entity\Acceso $idacceso
     */
    public function removeIdacceso(\SIGESRHI\AdminBundle\Entity\Acceso $idacceso)
    {
        $this->idacceso->removeElement($idacceso);
    }

    /**
     * Get idacceso
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getIdacceso()
    {
        return $this->idacceso;
    }
    
   public function __toString()
    {
        return $this->getName();
    }
}