expediente_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: ExpedienteBundle:Default:index }


ExpedienteBundle_solicitud:
        resource: "@ExpedienteBundle/Resources/config/routing/solicitudempleo.yml"
        prefix:   /solicitud


ExpedienteBundle_datosempleo:
        resource: "@ExpedienteBundle/Resources/config/routing/datosempleo.yml"
        prefix:   /datosempleo

ExpedienteBundle_datosfamiliares:
        resource: "@ExpedienteBundle/Resources/config/routing/datosfamiliares.yml"
        prefix:   /datosfamiliares