expediente_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: ExpedienteBundle:Default:index }

ExpedienteBundle_solicitud:
        resource: "@ExpedienteBundle/Resources/config/routing/solicitudempleo.yml"
        prefix:   /solicitud

ExpedienteBundle_segurovida:
        resource: "@ExpedienteBundle/Resources/config/routing/segurovida.yml"
        prefix:   /segurovida

ExpedienteBundle_beneficiario:
        resource: "@ExpedienteBundle/Resources/config/routing/beneficiario.yml"
        prefix:   /beneficiario
        
ExpedienteBundle_pruebapsicologica:
        resource: "@ExpedienteBundle/Resources/config/routing/pruebapsicologica.yml"
        prefix:   /pruebapsicologica

ExpedienteBundle_consultarMunicipiosJSON:
    pattern:  /solicitud/consultarMunicipiosJSON    
    defaults: { _controller: ExpedienteBundle:Solicitudempleo:consultarMunicipiosJSON }

ExpedienteBundle_Editar_consultarMunicipiosJSON:
    pattern:  /solicitud/{slug}/consultarMunicipiosJSON    
    defaults: { _controller: ExpedienteBundle:Solicitudempleo:consultarMunicipiosJSON }

ExpedienteBundle_docdigital:
       resource: "@ExpedienteBundle/Resources/config/routing/docexpediente.yml"
       prefix:   /docdigital

ExpedienteBundle_expediente:
       resource: "@ExpedienteBundle/Resources/config/routing/expediente.yml"
       prefix:   /expediente

ExpedienteBundle_contratacion:
        resource: "@ExpedienteBundle/Resources/config/routing/contratacion.yml"
        prefix:   /contratacion

ExpedienteBundle_docpersonal:
        resource: "@ExpedienteBundle/Resources/config/routing/docpersonal.yml"
        prefix:   /docpersonal


