parameters:
#    expediente.example.class: SIGESRHI\ExpedienteBundle\Example

services:
#    expediente.example:
#        class: %expediente.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]


# src/Acme/DemoBundle/Resources/config/services.yml

    expediente.fecha_extension:
        class: SIGESRHI\ExpedienteBundle\Twig\FechaExtension
        tags:
                - { name: twig.extension }

    expediente.dui_extension:
        class: SIGESRHI\ExpedienteBundle\Twig\DuiExtension
        tags:
                - { name: twig.extension }

    expediente.nit_extension:
        class: SIGESRHI\ExpedienteBundle\Twig\NitExtension
        tags:
                - { name: twig.extension }

    expediente.telefono_extension:
        class: SIGESRHI\ExpedienteBundle\Twig\TelefonoExtension
        tags:
                - { name: twig.extension }