accionpersonal_show:
    pattern:  /{id}/show
    defaults: { _controller: "ExpedienteBundle:Accionpersonal:show" }

accionpersonal_new:
    pattern:  /new
    defaults: { _controller: "ExpedienteBundle:Accionpersonal:new"}

accionpersonal_create:
    pattern:  /create
    defaults: { _controller: "ExpedienteBundle:Accionpersonal:create" }
    requirements: { _method: post }

accionpersonal_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "ExpedienteBundle:Accionpersonal:edit" }

accionpersonal_update:
    pattern:  /{id}/update
    defaults: { _controller: "ExpedienteBundle:Accionpersonal:update" }
    requirements: { _method: post|put }

accionpersonal_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "ExpedienteBundle:Accionpersonal:delete" }
    requirements: { _method: post|delete }

accionpersonal_consultarTipoAccionJSON:
    pattern:  /consultarTipoAccionJSON    
    defaults: { _controller: ExpedienteBundle:Accionpersonal:consultarTipoAccionJSON }

accionpersonal_cempleados:
    pattern:  /cempleados
    defaults: { _controller: "ExpedienteBundle:Accionpersonal:ConsultarEmpleadosAcuerdos" }

accionpersonal_cacuerdos:
    pattern:  /cacuerdos/{id}
    defaults: { _controller: "ExpedienteBundle:Accionpersonal:ConsultarAcuerdosEmpleado" }

accionpersonal_eligereporte:
    pattern:  /eligereporte/{id}
    defaults: { _controller: "ExpedienteBundle:Accionpersonal:ElegirReporte" }

accionpersonal_llamareporte:
    pattern:  /llamareporte/{id}
    defaults: { _controller: "ExpedienteBundle:Accionpersonal:LlamarReporte" }

accionpersonal_cempleadosotros:
    pattern:  /cempleadosotros
    defaults: { _controller: "ExpedienteBundle:Accionpersonal:ConsultarEmpleadosOtrosAcuerdos" }

accionpersonal_cotrosacuerdos:
    pattern:  /cotrosacuerdos/{id}
    defaults: { _controller: "ExpedienteBundle:Accionpersonal:ConsultarOtrosAcuerdosEmpleado" }

accionpersonal_new_otros:
    pattern:  /newotros
    defaults: { _controller: "ExpedienteBundle:Accionpersonal:NuevaOtraAccion"}

accionpersonal_create_otros:
    pattern:  /createotros
    defaults: { _controller: "ExpedienteBundle:Accionpersonal:CrearOtraAccion" }
    requirements: { _method: post }

accionpersonal_rempleados:
    pattern:  /rempleados
    defaults: { _controller: "ExpedienteBundle:Accionpersonal:RegistrarEmpleadosAcuerdos" }

accionpersonal_rempleadosotros:
    pattern:  /rempleadosotros
    defaults: { _controller: "ExpedienteBundle:Accionpersonal:RegistrarEmpleadosOtrosAcuerdos" }
