concurso:
    pattern:  /
    defaults: { _controller: "ExpedienteBundle:Concurso:index" }

concurso_consultar:
    pattern:  /consultar
    defaults: { _controller: "ExpedienteBundle:Concurso:consultar" }

concurso_show:
    pattern:  /{id}/show
    defaults: { _controller: "ExpedienteBundle:Concurso:show" }

concurso_new:
    pattern:  /new
    defaults: { _controller: "ExpedienteBundle:Concurso:new" }

concurso_create:
    pattern:  /create
    defaults: { _controller: "ExpedienteBundle:Concurso:create" }
    requirements: { _method: post }

concurso_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "ExpedienteBundle:Concurso:edit" }

concurso_update:
    pattern:  /{id}/update
    defaults: { _controller: "ExpedienteBundle:Concurso:update" }
    requirements: { _method: post|put }

concurso_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "ExpedienteBundle:Concurso:delete" }
    requirements: { _method: post|delete }

concurso_memo:
    pattern:  /memorandum
    defaults: { _controller: "ExpedienteBundle:Concurso:generarMemorandum" }

detalle_concurso:
    pattern:  /detalleconcurso
    defaults: { _controller: "ExpedienteBundle:Concurso:detalleConcurso" }

memo_cierre:
    pattern:  /memorandumcierre
    defaults: { _controller: "ExpedienteBundle:Concurso:memoCierre" }

acta_cierre:
    pattern:  /actacierre
    defaults: { _controller: "ExpedienteBundle:Concurso:ActaCierre" }

concurso_consultarCargosJSON:
    pattern:  /consultarCargosJSON    
    defaults: { _controller: "ExpedienteBundle:Concurso:consultarCargosJSON" }

