contratacion:
    pattern:  /
    defaults: { _controller: "ExpedienteBundle:Contratacion:registrar" }

contratacion_consultar:
    pattern:  /consultar
    defaults: { _controller: "ExpedienteBundle:Contratacion:consultar" }

contratacion_empleado:
    pattern:  /registrar
    defaults: { _controller: "ExpedienteBundle:Contratacion:registrarEmpleado" }

contratacion_show:
    pattern:  /{id}/{tipo}/show
    defaults: { _controller: "ExpedienteBundle:Contratacion:show",tipo: 0 }

contratacion_new:
    pattern:  /new
    defaults: { _controller: "ExpedienteBundle:Contratacion:new" }

contratacion_create:
    pattern:  /create
    defaults: { _controller: "ExpedienteBundle:Contratacion:create" }
    requirements: { _method: post }

contratacion_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "ExpedienteBundle:Contratacion:edit" }

contratacion_update:
    pattern:  /{id}/update
    defaults: { _controller: "ExpedienteBundle:Contratacion:update" }
    requirements: { _method: post|put }

contratacion_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "ExpedienteBundle:Contratacion:delete" }
    requirements: { _method: post|delete }

contratacion_tipo:
    pattern:  /tipo
    defaults: { _controller: "ExpedienteBundle:Contratacion:tipoContrato" }

carta_trabajo:
    pattern:  /cartatrabajo
    defaults: { _controller: "ExpedienteBundle:Contratacion:cartaTrabajo" }
