datosfamiliares:
    pattern:  /
    defaults: { _controller: "ExpedienteBundle:Datosfamiliares:index" }

datosfamiliares_show:
    pattern:  /{id}/show
    defaults: { _controller: "ExpedienteBundle:Datosfamiliares:show" }

datosfamiliares_new:
    pattern:  /new
    defaults: { _controller: "ExpedienteBundle:Datosfamiliares:new" }

datosfamiliares_create:
    pattern:  /create
    defaults: { _controller: "ExpedienteBundle:Datosfamiliares:create" }
    requirements: { _method: post }

datosfamiliares_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "ExpedienteBundle:Datosfamiliares:edit" }

datosfamiliares_update:
    pattern:  /{id}/update
    defaults: { _controller: "ExpedienteBundle:Datosfamiliares:update" }
    requirements: { _method: post|put }

datosfamiliares_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "ExpedienteBundle:Datosfamiliares:delete" }
    requirements: { _method: post|delete }
