docpersonal:
    pattern:  /aspirante
    defaults: { _controller: "ExpedienteBundle:Docpersonal:index" }

docpersonal_show:
    pattern:  /{id}/show
    defaults: { _controller: "ExpedienteBundle:Docpersonal:show" }

docpersonal_new:
    pattern:  /new/aspirante
    defaults: { _controller: "ExpedienteBundle:Docpersonal:new" }

docpersonal_create:
    pattern:  /create
    defaults: { _controller: "ExpedienteBundle:Docpersonal:create" }
    requirements: { _method: post }

docpersonal_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "ExpedienteBundle:Docpersonal:edit" }

docpersonal_update:
    pattern:  /{id}/update
    defaults: { _controller: "ExpedienteBundle:Docpersonal:update" }
    requirements: { _method: post|put }

docpersonal_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "ExpedienteBundle:Docpersonal:delete" }
    requirements: { _method: post|delete }

docpersonal_empleado:
    pattern:  /empleado
    defaults: { _controller: "ExpedienteBundle:Docpersonal:indexEmpleado" }

docpersonal_new_empleado:
    pattern:  /new/empleado
    defaults: { _controller: "ExpedienteBundle:Docpersonal:newEmpleado" }