empleadoconcurso:
    pattern:  /
    defaults: { _controller: "ExpedienteBundle:Empleadoconcurso:index" }

empleadoconcurso_show:
    pattern:  /{id}/show
    defaults: { _controller: "ExpedienteBundle:Empleadoconcurso:show" }

empleadoconcurso_new:
    pattern:  /new
    defaults: { _controller: "ExpedienteBundle:Empleadoconcurso:new" }

empleadoconcurso_create:
    pattern:  /create
    defaults: { _controller: "ExpedienteBundle:Empleadoconcurso:create" }
    requirements: { _method: post }

empleadoconcurso_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "ExpedienteBundle:Empleadoconcurso:edit" }

empleadoconcurso_update:
    pattern:  /{id}/update
    defaults: { _controller: "ExpedienteBundle:Empleadoconcurso:update" }
    requirements: { _method: post|put }

empleadoconcurso_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "ExpedienteBundle:Empleadoconcurso:delete" }
