expediente:
    pattern:  /
    defaults: { _controller: "ExpedienteBundle:Expediente:index" }

expediente_show:
    pattern:  /{id}/show
    defaults: { _controller: "ExpedienteBundle:Expediente:show" }

expediente_new:
    pattern:  /new
    defaults: { _controller: "ExpedienteBundle:Expediente:new" }

expediente_create:
    pattern:  /create
    defaults: { _controller: "ExpedienteBundle:Expediente:create" }
    requirements: { _method: post }

expediente_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "ExpedienteBundle:Expediente:edit" }

expediente_update:
    pattern:  /{id}/update
    defaults: { _controller: "ExpedienteBundle:Expediente:update" }
    requirements: { _method: post|put }

expediente_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "ExpedienteBundle:Expediente:delete" }
    requirements: { _method: post|delete }

expediente_RegistraDocDigi:
    pattern:  /{id}/DocDigital
    defaults: { _controller: "ExpedienteBundle:Expediente:registraDocDigi" }

expediente_validar:
    pattern:  /validar
    defaults: { _controller: "ExpedienteBundle:Expediente:validar" }

expediente_confirm_valid:
    pattern:  /{id}/validar
    defaults: { _controller: "ExpedienteBundle:Expediente:confirmarValido" }

expediente_aspirantes:
    pattern:  /aspirantes
    defaults: { _controller: "ExpedienteBundle:Expediente:indexAspirantes" }

expediente_elim_ant:
    pattern:  /aspirantes/ant
    defaults: { _controller: "ExpedienteBundle:Expediente:antAspirantes" }

expediente_elim_indv:
    pattern:  /aspirantes/indv
    defaults: { _controller: "ExpedienteBundle:Expediente:indvAspirantes" }