expediente:
    pattern:  /
    defaults: { _controller: "ExpedienteBundle:Expediente:index" }

expediente_show:
    pattern:  /{id}/show
    defaults: { _controller: "ExpedienteBundle:Expediente:show" }

expediente_new:
    pattern:  /new
    defaults: { _controller: "ExpedienteBundle:Expediente:new" }

expediente_create:
    pattern:  /create
    defaults: { _controller: "ExpedienteBundle:Expediente:create" }
    requirements: { _method: post }

expediente_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "ExpedienteBundle:Expediente:edit" }

expediente_update:
    pattern:  /{id}/update
    defaults: { _controller: "ExpedienteBundle:Expediente:update" }
    requirements: { _method: post|put }

expediente_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "ExpedienteBundle:Expediente:delete" }
    requirements: { _method: post|delete }

expediente_RegistraDocDigi:
    pattern:  /{id}/DocDigital
    defaults: { _controller: "ExpedienteBundle:Expediente:registraDocDigi" }

expediente_validar:
    pattern:  /validar
    defaults: { _controller: "ExpedienteBundle:Expediente:validar" }

expediente_confirm_valid:
    pattern:  /{id}/confirmarvalido
    defaults: { _controller: "ExpedienteBundle:Expediente:confirmarValido" }

expediente_aspirantes:
    pattern:  /aspirantes
    defaults: { _controller: "ExpedienteBundle:Expediente:indexAspirantes" }

eliminar_aspirantes:
    pattern: /aspirantes/eliminar
    defaults: { _controller: "ExpedienteBundle:Expediente:eliminarAspirante" }

expediente_elim_ant:
    pattern:  /aspirantes/eliminar/ant
    defaults: { _controller: "ExpedienteBundle:Expediente:antAspirantes" }

expediente_elim_indv:
    pattern:  /aspirantes/eliminar/indv
    defaults: { _controller: "ExpedienteBundle:Expediente:indvAspirantes" }

expediente_aelim:
    pattern: /aspirantes/eliminar/ant/list
    defaults: { _controller: "ExpedienteBundle:Expediente:showElim" }

eliminar_aspirantes_confirm:
    pattern: /aspirantes/eliminar/confirmar
    defaults: { _controller: "ExpedienteBundle:Expediente:confirmarEliminacion" }

expediente_adm_empleado:
    pattern:  /empleado/activo
    defaults: { _controller: "ExpedienteBundle:Expediente:admEmpleado" }

expediente_inactivar:
    pattern:  /empleado/inactivar
    defaults: { _controller: "ExpedienteBundle:Expediente:inactivarEmpleado" }

expediente_adm_empleado_inactivo:
    pattern:  /empleado/inactivo
    defaults: { _controller: "ExpedienteBundle:Expediente:admEmpleadoInactivo" }

expediente_activar:
    pattern:  /empleado/activar
    defaults: { _controller: "ExpedienteBundle:Expediente:activarEmpleado" }

consultar_estado:
    pattern:  /consultarestado
    defaults: { _controller: "ExpedienteBundle:Expediente:consultarEstado" }

consultar_persona:
    pattern: /estadoexpediente
    defaults: { _controller: "ExpedienteBundle:Expediente:estadoExpediente" }
