hojaservicio_new:
    pattern:  /{id}/{idc}/new
    defaults: { _controller: "ExpedienteBundle:Hojaservicio:new" }

hojaservicio_create:
    pattern:  /create
    defaults: { _controller: "ExpedienteBundle:Hojaservicio:create" }
    requirements: { _method: post }

