infacademica:
    pattern:  /
    defaults: { _controller: "ExpedienteBundle:Informacionacademica:index" }

infacademica_show:
    pattern:  /{id}/show
    defaults: { _controller: "ExpedienteBundle:Informacionacademica:show" }

infacademica_new:
    pattern:  /new
    defaults: { _controller: "ExpedienteBundle:Informacionacademica:new" }

infacademica_create:
    pattern:  /create
    defaults: { _controller: "ExpedienteBundle:Informacionacademica:create" }
    requirements: { _method: post }

infacademica_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "ExpedienteBundle:Informacionacademica:edit" }

infacademica_update:
    pattern:  /{id}/update
    defaults: { _controller: "ExpedienteBundle:Informacionacademica:update" }
    requirements: { _method: post|put }

infacademica_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "ExpedienteBundle:Informacionacademica:delete" }
    requirements: { _method: post|delete }
