licencia:
    pattern:  /{opc}
    defaults: { _controller: "ExpedienteBundle:Licencia:index" }

licencia_ver:
    pattern:  /indexver
    defaults: { _controller: "ExpedienteBundle:Licencia:indexVer" }

licencia_registrar:
    pattern:  /indexregistrar
    defaults: { _controller: "ExpedienteBundle:Licencia:indexRegistrar" }

licencia_show:
    pattern:  /{id}/show
    defaults: { _controller: "ExpedienteBundle:Licencia:show" }

licencia_new:
    pattern:  /{id}/new
    defaults: { _controller: "ExpedienteBundle:Licencia:new" }

licencia_create:
    pattern:  /create
    defaults: { _controller: "ExpedienteBundle:Licencia:create" }
    requirements: { _method: post }