licencia_ver:
    pattern:  /indexver
    defaults: { _controller: "ExpedienteBundle:Licencia:indexVer" }

licencia_ver_permisos:
    pattern:  /{id}/{idc}/indexverpermisos
    defaults: { _controller: "ExpedienteBundle:Licencia:indexVerPermisos" }

licencia_registrar:
    pattern:  /indexregistrar
    defaults: { _controller: "ExpedienteBundle:Licencia:indexRegistrar" }

licencia_show:
    pattern:  /{id}/show
    defaults: { _controller: "ExpedienteBundle:Licencia:show" }

licencia_new:
    pattern:  /{id}/new
    defaults: { _controller: "ExpedienteBundle:Licencia:new" }

licencia_create:
    pattern:  /create
    defaults: { _controller: "ExpedienteBundle:Licencia:create" }
    requirements: { _method: post }

licencia_edit:
    pattern: /{id}/edit
    defaults: { _controller: "ExpedienteBundle:Licencia:edit" }

licencia_delete:
    pattern:  /{id}/{cf}/delete
    defaults: { _controller: "ExpedienteBundle:Licencia:delete" }
    requirements: { _method: post|delete }

verReporteLicencias:
    pattern:  /{idc}/reporte
    defaults: { _controller: "ExpedienteBundle:Licencia:verReporteLicencias" }
