#pruebapsicologica:
#    pattern:  /
#    defaults: { _controller: "ExpedienteBundle:Pruebapsicologica:index" }

pruebapsicologica:
    pattern:  /indexnew
    defaults: { _controller: "ExpedienteBundle:Pruebapsicologica:indexExpedientes" }

pruebapsicologica_show:
    pattern:  /{id}/show
    defaults: { _controller: "ExpedienteBundle:Pruebapsicologica:show" }

pruebapsicologica_new:
    pattern:  /{id}/new
    defaults: { _controller: "ExpedienteBundle:Pruebapsicologica:new" }

pruebapsicologica_create:
    pattern:  /create
    defaults: { _controller: "ExpedienteBundle:Pruebapsicologica:create" }
    requirements: { _method: post }

pruebapsicologica_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "ExpedienteBundle:Pruebapsicologica:edit" }

pruebapsicologica_update:
    pattern:  /update
    defaults: { _controller: "ExpedienteBundle:Pruebapsicologica:update" }
    requirements: { _method: post|put }

pruebapsicologica_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "ExpedienteBundle:Pruebapsicologica:delete" }
    requirements: { _method: post|delete }

pruebapsicologica_index_edit:
    pattern:  /indexedit
    defaults: { _controller: "ExpedienteBundle:Pruebapsicologica:indexExpedientesEdit" }