solicitud_caspirante:
    pattern:  /consultaraspirante
    defaults: { _controller: "ExpedienteBundle:Solicitudempleo:ConsultarSolicitudAspirante" }

solicitud_show:
    pattern:  /{id}/show
    defaults: { _controller: "ExpedienteBundle:Solicitudempleo:show" }

solicitud_new:
    pattern:  /new
    defaults: { _controller: "ExpedienteBundle:Solicitudempleo:new" }

solicitud_create:
    pattern:  /create
    defaults: { _controller: "ExpedienteBundle:Solicitudempleo:create" }
    requirements: { _method: post }

solicitud_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "ExpedienteBundle:Solicitudempleo:edit" }

solicitud_update:
    pattern:  /{id}/update
    defaults: { _controller: "ExpedienteBundle:Solicitudempleo:update" }
    requirements: { _method: post|put }

solicitud_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "ExpedienteBundle:Solicitudempleo:delete" }
    requirements: { _method: post|delete }

solicitud_maspirante:
    pattern:  /editaraspirante
    defaults: { _controller: "ExpedienteBundle:Solicitudempleo:EditarSolicitudAspirante" }

solicitud_pruebanumsol:
    pattern:  /pruebanumsol/{id}
    defaults: { _controller: "ExpedienteBundle:Solicitudempleo:asignarNumsol" }

solicitud_cempleado:
    pattern:  /consultarempleado
    defaults: { _controller: "ExpedienteBundle:Solicitudempleo:ConsultarSolicitudEmpleado" }

solicitud_cinactivo:
    pattern:  /consultarinactivo
    defaults: { _controller: "ExpedienteBundle:Solicitudempleo:ConsultarSolicitudInactivo" }

solicitud_mempleado:
    pattern:  /editarempleado
    defaults: { _controller: "ExpedienteBundle:Solicitudempleo:EditarSolicitudEmpleado" }