imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: "@AdminBundle/Resources/config/admin.yml" }

framework:
    #esi:             ~
    translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: %kernel.debug%
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "es"
    trusted_proxies: ~
    session:         ~
    fragments:       ~

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

    form:
        resources:
            - ShtumiUsefulBundle::fields.html.twig
            - PcdummyAjaxCompleteBundle::fields.html.twig


# Assetic Configuratio
assetic:
    debug:          %kernel.debug%
    use_controller: false
    #bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        #yui_css:
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
        types:
           json: Sonata\Doctrine\Types\JsonType
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: %kernel.root_dir%/data/data.db3
        # path:     %database_path%

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }

#FOS User
fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: Application\Sonata\UserBundle\Entity\User
    group:
        group_class:  Application\Sonata\UserBundle\Entity\Group

    profile:  # Authentication Form
        form:
            type:               fos_user_profile
            handler:            fos_user.profile.form.handler.default
            name:               fos_user_profile_form
            validation_groups:  [Authentication] 

#Sonata admin & user
sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.admin_list:
            contexts:   [admin]

        sonata.block.service.text:   ~
        sonata.block.service.action: ~
        sonata.block.service.rss:    ~

sonata_admin:
    title:      'SIGESRHI - Administrador'
    title_logo: images/Logo_ISRI.png
    templates:
        # plantillas globales predefinidas
        ajax:    SonataAdminBundle::ajax_layout.html.twig
        preview: SonataAdminBundle:CRUD:preview.html.twig
    dashboard:
        blocks:
           - { position: left, type: sonata.admin.block.admin_list }
           - { position: right, type: sonata.block.service.text, settings: { content: "<h2>Area de administración</h2> <p style='font-size:16px' >En esta sección podra llevar a cabo las configuraciones para usuarios, roles y sus respectivos accesos a modulos del sistema. <br /><br /> De igual forma podrá realizar la gestión de los centros de atención, unidades organizativas y la administración para el manual de puestos de la institución.</p>"} }
        
sonata_user:
    profile:
      form:
            type:               sonata_user_profile
            handler:            sonata.user.profile.form.handler.default
            name:               sonata_user_profile_form
            validation_groups:  [Profile]

#Bootstrap
parameters:
    mopa_bootstrap.form.render_optional_text: false

# Vich
knp_gaufrette:
    adapters:
        docsexp_adapter:
            local:
                directory: %kernel.root_dir%/../web/uploads/docs_expediente
        fotografia_adapter:
            local:
                directory: %kernel.root_dir%/../web/uploads/fotografias

    filesystems:
        docs_exp_fs:
            adapter:    docsexp_adapter
        fotografia_fs:
            adapter:    fotografia_adapter

vich_uploader:
    db_driver: orm
    gaufrette: true
    storage: vich_uploader.storage.gaufrette
    mappings:
        docs_expediente:
            uri_prefix: docsexp_adapter
            upload_destination: docs_exp_fs 
            namer: vich_uploader.namer_origname
            delete_on_remove: true
            delete_on_update: true

        fotografias:
            uri_prefix: fotografia_adapter
            upload_destination: fotografia_fs 
            namer: vich_uploader.namer_origname
            delete_on_remove: true
            delete_on_update: true

#Breadcrumbs
white_october_breadcrumbs: 
    separator:          /
    separatorClass:     divider
    listId:             wo-breadcrumbs
    listClass:          breadcrumb          

#Autocomplete
genemu_form:
    select2: ~
    autocomplete: ~

shtumi_useful:
    autocomplete_entities:
        empleados:
            class: ExpedienteBundle:Solicitudempleo
            property: nombrecompleto
            search: contains
        codigos:
            class: ExpedienteBundle:Empleado
            property: codigoempleado
            search: contains
        plazas:
            class: AdminBundle:Plaza
            property: nombreplaza
            search: contains
