sigesrhi_portal_empleado:
    resource: "@SIGESRHIPortalEmpleadoBundle/Resources/config/routing.yml"
    prefix:   /

capacitacion:
    resource: "@CapacitacionBundle/Resources/config/routing.yml"
    prefix:   /capacitacion

evaluacion:
    resource: "@EvaluacionBundle/Resources/config/routing.yml"
    prefix:   /evaluacion

reporte:
    resource: "@ReporteBundle/Resources/config/routing.yml"
    prefix:   /reporte

expediente:
    resource: "@ExpedienteBundle/Resources/config/routing.yml"
    prefix:   /expediente

_user_bundle:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

shtumi_useful:
    resource: '@ShtumiUsefulBundle/Resources/config/routing.xml'
