reporte:
    resource: "@ReporteBundle/Resources/config/routing.yml"
    prefix:   /

expediente:
    resource: "@ExpedienteBundle/Resources/config/routing.yml"
    prefix:   /expediente

_user_bundle:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin
