jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:        [ROLE_USER, ROLE_SONATA_ADMIN, ROLE_EMPLEADORRHH, ROLE_JEFERRHH, ROLE_JEFEUNIDAD, ROLE_EMPLEADO, ROLE_DIRECTOR, ROLE_PSICOLOGO]
        ROLE_SUPER_ADMIN:  [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
        ROLE_EMPLEADO:     [ROLE_USER]
        ROLE_PSICOLOGO:    [ROLE_USER]
        ROLE_JEFEUNIDAD:   [ROLE_USER]
        ROLE_DIRECTOR:     [ROLE_USER, ROLE_JEFEUNIDAD]
        ROLE_EMPLEADORRHH: [ROLE_USER, ROLE_PSICOLOGO]
        ROLE_JEFERRHH:     [ROLE_USER, ROLE_EMPLEADORRHH, ROLE_JEFEUNIDAD]

    providers:
        fos_userbundle:
            id: fos_user.user_manager

    firewalls:
        main:
            pattern:    ^/
            form_login:
                check_path: /login_check
                login_path: /
                provider: fos_userbundle
                use_referer: true
                success_handler: security.authentication.success_handler
            logout:
                path:   /admin/logout
                target: /
            anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        # - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        # Change these rules to adapt them to your needs
        - { path: ^/expediente/solicitud/new, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/expediente/solicitud/create, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/expediente/docdigital/new, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/expediente/docdigital/documento, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/expediente/docdigital/[^/]+/create, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/expediente/docdigital/fin, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/expediente/solicitud/consultarMunicipiosJSON, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/expediente/pruebapsicologica/, role: [ROLE_PSICOLOGO] }
        - { path: ^/reporte/reportepruebapsicologica, role: [ROLE_PSICOLOGO] }
        - { path: ^/reporte/reporteevaluacionI, role: [ROLE_DIRECTOR] }
        - { path: ^/reporte/reporteevaluaciones, role: [ROLE_DIRECTOR] }
        - { path: ^/reporte/reporteevaluacion, role: [ROLE_JEFEUNIDAD] }
        - { path: ^/evaluacion/evaluar/, role: [ROLE_JEFEUNIDAD] }
        - { path: ^/capacitacion/solicitud/capacitacion/, role: [ROLE_JEFEUNIDAD] }
        - { path: ^/expediente/noticia/indexempleado, role: [ROLE_EMPLEADO] }
        - { path: ^/expediente/noticia/[^/]+/showEmpleado, role: [ROLE_EMPLEADO] }
        - { path: ^/admin/*, role: [ROLE_ADMIN, ROLE_SONATA_ADMIN] }
        - { path: ^/expediente/*, role: [ROLE_EMPLEADORRHH] }
        - { path: ^/reporte/*, role: [ROLE_EMPLEADORRHH] }
        - { path: ^/evaluacion/*, role: [ROLE_JEFERRHH] }
        - { path: ^/capacitacion/*, role: [ROLE_JEFERRHH, ROLE_DIRECTOR] }
        - { path: ^/.*, role: IS_AUTHENTICATED_ANONYMOUSLY }