jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:        [ROLE_USER, ROLE_SONATA_ADMIN, ROLE_EMPLEADORRHH, ROLE_JEFERRHH]
        ROLE_SUPER_ADMIN:  [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
        ROLE_EMPLEADORRHH: [ROLE_USER]
        ROLE_JEFERRHH:     [ROLE_USER,ROLE_EMPLEADORRHH]

    providers:
        fos_userbundle:
            id: fos_user.user_manager

    firewalls:
        main:
            pattern:    ^/
            form_login:
                check_path: /login_check
                login_path: /
                provider: fos_userbundle
                use_referer: true
                success_handler: security.authentication.success_handler
            logout:
                path:   /admin/logout
                target: /
            anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        # - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        # Change these rules to adapt them to your needs
        - { path: ^/expediente/solicitud/new, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/expediente/solicitud/create, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/expediente/docdigital/new, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/expediente/docdigital/documento, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/expediente/docdigital/[^/]+/create, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/expediente/docdigital/fin, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/expediente/solicitud/consultarMunicipiosJSON, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: [ROLE_ADMIN, ROLE_SONATA_ADMIN] }
        - { path: ^/expediente/, role: [ROLE_EMPLEADORRHH] }
        - { path: ^/.*, role: IS_AUTHENTICATED_ANONYMOUSLY }