<?php

namespace SIGESRHI\PortalEmpleadoBundle\Repositorio;

use Doctrine\ORM\EntityRepository;

/**
 * PlancapacitacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SolicitudcapacitacionRepository extends EntityRepository
{

  /**
   * Descripción: Función utilizada para obtener los jefes de empleado con mas de una plaza 
   * Retorno:     Id de empleado, nombrecompleto
   * Author:      Roquet  
   */
	public function obtenerJefe($idempleado)
    {
          return $this->getEntityManager()
                      ->createQuery('SELECT e.id, r.nombreplaza puesto
                                     FROM ExpedienteBundle:Solicitudempleo s
                                     JOIN s.idexpediente ex
                                     JOIN ex.idempleado e
                                     JOIN e.idrefrenda r
                                     WHERE r.id in (
                                        SELECT IDENTITY (c.puestojefe)
                                        FROM AdminBundle:RefrendaAct ra
                                        JOIN ra.puestoempleado c
                                        WHERE ra.idempleado = :idempleado) 
                                     ')
                     ->setParameter('idempleado', $idempleado)
                     ->getResult();
    }

}  