centrounidad:
    pattern:  /
    defaults: { _controller: "AdminBundle:Centrounidad:index" }

centrounidad_show:
    pattern:  /{id}/show
    defaults: { _controller: "AdminBundle:Centrounidad:show" }

centrounidad_new:
    pattern:  /new
    defaults: { _controller: "AdminBundle:Centrounidad:new" }

centrounidad_create:
    pattern:  /create
    defaults: { _controller: "AdminBundle:Centrounidad:create" }
    requirements: { _method: post }

centrounidad_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "AdminBundle:Centrounidad:edit" }

centrounidad_update:
    pattern:  /{id}/update
    defaults: { _controller: "AdminBundle:Centrounidad:update" }
    requirements: { _method: post|put }

centrounidad_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "AdminBundle:Centrounidad:delete" }
    requirements: { _method: post|delete }
