modulo:
    pattern:  /
    defaults: { _controller: "AdminBundle:Modulo:index" }

modulo_show:
    pattern:  /{id}/show
    defaults: { _controller: "AdminBundle:Modulo:show" }

modulo_new:
    pattern:  /new
    defaults: { _controller: "AdminBundle:Modulo:new" }

modulo_create:
    pattern:  /create
    defaults: { _controller: "AdminBundle:Modulo:create" }
    requirements: { _method: post }

modulo_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "AdminBundle:Modulo:edit" }

modulo_update:
    pattern:  /{id}/update
    defaults: { _controller: "AdminBundle:Modulo:update" }
    requirements: { _method: post|put }

modulo_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "AdminBundle:Modulo:delete" }
    requirements: { _method: post|delete }
