noticia:
    pattern:  /
    defaults: { _controller: "AdminBundle:Noticia:index" }

noticia_show:
    pattern:  /{id}/show
    defaults: { _controller: "AdminBundle:Noticia:show" }

noticia_new:
    pattern:  /new
    defaults: { _controller: "AdminBundle:Noticia:new" }

noticia_create:
    pattern:  /create
    defaults: { _controller: "AdminBundle:Noticia:create" }
    requirements: { _method: post }

noticia_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "AdminBundle:Noticia:edit" }

noticia_update:
    pattern:  /{id}/update
    defaults: { _controller: "AdminBundle:Noticia:update" }
    requirements: { _method: post|put }

noticia_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "AdminBundle:Noticia:delete" }
    requirements: { _method: post|delete }

noticia_indexdelete:
    pattern:  /indexeliminar
    defaults: { _controller: "AdminBundle:Noticia:indexEliminar" }

noticia_confirm_delete:
    pattern:  /{id}/confirmdelete
    defaults: { _controller: "AdminBundle:Noticia:confirmdelete" }
