pantalla_modulo:
    pattern:  /{id}/modulo
    defaults: { _controller: "AdminBundle:Pantallas:pantallaModulo" }

pantalla_aspirante:
    pattern:  /aspirante
    defaults: { _controller: "AdminBundle:Pantallas:pantallaAspirante" }

pantalla_empleadoactivo:
    pattern:  /empleadoactivo
    defaults: { _controller: "AdminBundle:Pantallas:pantallaEmpleadoActivo" }

pantalla_empleadoinactivo:
    pattern:  /empleadoinactivo
    defaults: { _controller: "AdminBundle:Pantallas:pantallaEmpleadoInactivo" }

pantalla_capacitaciones:
    pattern:  /capacitaciones
    defaults: { _controller: "AdminBundle:Pantallas:pantallaCapacitaciones" }

pantalla_instituciones:
    pattern:  /instituciones
    defaults: { _controller: "AdminBundle:Pantallas:pantallaInstituciones" }

pantalla_facilitadores:
    pattern:  /facilitadores
    defaults: { _controller: "AdminBundle:Pantallas:pantallaFacilitadores" }

pantalla_documentos:
    pattern:  /documentos
    defaults: { _controller: "AdminBundle:Pantallas:pantallaDocumentos" }

pantalla_reportes:
    pattern:  /reportes
    defaults: { _controller: "AdminBundle:Pantallas:pantallaReportes" }

pantalla_evaluacion:
    pattern:  /evaluacion
    defaults: { _controller: "AdminBundle:Pantallas:pantallaRealizarEvaluacion" }

pantalla_formularios:
    pattern:  /formularios
    defaults: { _controller: "AdminBundle:Pantallas:pantallaFormulariosEvaluacion" }