refrenda:
    pattern:  /
    defaults: { _controller: "AdminBundle:Refrenda:index" }

refrenda_cargar:
    pattern:  /cargar
    defaults: { _controller: "AdminBundle:Refrenda:cargar" }

refrenda_verificar:
    pattern:  /verificar
    defaults: { _controller: "AdminBundle:Refrenda:verificar" }

cargar_inicial:
    pattern:  /cargainicial
    defaults: { _controller: "AdminBundle:Refrenda:cargaInicial" }

carga_inicial_verificar:
    pattern:  /cargainicialverificar
    defaults: { _controller: "AdminBundle:Refrenda:verificarCargaInicial" }
