unidadorganizativa:
    pattern:  /
    defaults: { _controller: "AdminBundle:Unidadorganizativa:index" }

unidadorganizativa_show:
    pattern:  /{id}/show
    defaults: { _controller: "AdminBundle:Unidadorganizativa:show" }

unidadorganizativa_new:
    pattern:  /new
    defaults: { _controller: "AdminBundle:Unidadorganizativa:new" }

unidadorganizativa_create:
    pattern:  /create
    defaults: { _controller: "AdminBundle:Unidadorganizativa:create" }
    requirements: { _method: post }

unidadorganizativa_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "AdminBundle:Unidadorganizativa:edit" }

unidadorganizativa_update:
    pattern:  /{id}/update
    defaults: { _controller: "AdminBundle:Unidadorganizativa:update" }
    requirements: { _method: post|put }

unidadorganizativa_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "AdminBundle:Unidadorganizativa:delete" }
    requirements: { _method: post|delete }
