factorevaluacion_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "EvaluacionBundle:Factorevaluacion:delete" }
    requirements: { _method: post|delete }

factorevaluacion_newfactor:
    pattern:  /{id}/newfactor
    defaults: { _controller: "EvaluacionBundle:Factorevaluacion:newfactor" }

factorevaluacion_createfactor:
    pattern:  /createfactor
    defaults: { _controller: "EvaluacionBundle:Factorevaluacion:createFactor" }
    requirements: { _method: post }

factorevaluacion_editfactor:
    pattern:  /{id}/editfactor
    defaults: { _controller: "EvaluacionBundle:Factorevaluacion:editFactor" }

factorevaluacion_updatefactor:
    pattern:  /{id}/updatefactor
    defaults: { _controller: "EvaluacionBundle:Factorevaluacion:updateFactor" }
    requirements: { _method: post|put }

factorevaluacion_showfactor:
    pattern:  /{id}/showfactor
    defaults: { _controller: "EvaluacionBundle:Factorevaluacion:showFactor" }