opcion:
    pattern:  /
    defaults: { _controller: "EvaluacionBundle:Opcion:index" }

opcion_show:
    pattern:  /{id}/show
    defaults: { _controller: "EvaluacionBundle:Opcion:show" }

opcion_new:
    pattern:  /new
    defaults: { _controller: "EvaluacionBundle:Opcion:new" }

opcion_create:
    pattern:  /create
    defaults: { _controller: "EvaluacionBundle:Opcion:create" }
    requirements: { _method: post }

opcion_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "EvaluacionBundle:Opcion:edit" }

opcion_update:
    pattern:  /{id}/update
    defaults: { _controller: "EvaluacionBundle:Opcion:update" }
    requirements: { _method: post|put }

opcion_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "EvaluacionBundle:Opcion:delete" }
    requirements: { _method: post|delete }
