<?php

namespace SIGESRHI\ExpedienteBundle\Repositorio;

use Doctrine\ORM\EntityRepository;

/**
 * ContratacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContratacionRepository extends EntityRepository
{
	public function obtenerAspiranteValido($idexp)
    {
    return $this->getEntityManager()
            ->createQuery("SELECT s.id,
      	                          e.id idexpediente,
      	                          s.nombrecompleto, 
      	                          CONCAT(m.nombremunicipio,CONCAT(', ',d.nombredepartamento))  direccion, 
      	                          s.estadocivil, 
      	                          s.telefonofijo,
                                  s.telefonomovil, 
                                  s.email,
                                  s.lugarnac, 
                                  s.fechanac, 
                                  s.fotografia,
                                  s.dui,
                                  s.nit,
                                  s.isss,
                                  s.nup,
                                  s.nip,
                                  s.sexo,
                                  s.fechadui,
                                  s.lugardui,
                                  p.nombreplaza
                           FROM ExpedienteBundle:Solicitudempleo s JOIN s.idexpediente e join s.idplaza p
                           JOIN s.idmunicipio m JOIN m.iddepartamento d
                           WHERE e.id=:idexp
                           ")
            ->setParameter('idexp',$idexp)
            ->getResult();
  }
}