<?php

namespace SIGESRHI\ExpedienteBundle\Repositorio;

use Doctrine\ORM\EntityRepository;

/**
 * ExpedienteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExpedienteRepository extends EntityRepository
{
	public function obtenerExpedientes()
    {
		return $this->getEntityManager()
			->createQuery('SELECT e 
                           FROM ExpedienteBundle:Expediente e
                           WHERE e.porcentaje > 0.5
                           ORDER BY e.id ASC')
            ->getResult();
	}
}
