reporte_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: ReporteBundle:Default:index }

reporte_prueba:
    pattern:  /reporteprueba
    defaults: { _controller: ReporteBundle:Reporte:index }

reporte_create:
    pattern:  /reportecreate
    defaults: { _controller: ReporteBundle:Reporte:create }

reporte_segurovida:
    pattern:  /reporteseguro
    defaults: { _controller: ReporteBundle:Reporte:ReporteSeguroVida }

reporte_solicitudempleo:
    pattern:  /reportesolicitud
    defaults: { _controller: ReporteBundle:Reporte:ReporteSolicitud }

reporte_pruebapsicologica:
    pattern:  /reportepruebapsicologica
    defaults: { _controller: ReporteBundle:Reporte:ReportePruebaPsicologica }