reporte_segurovida:
    pattern:  /reporteseguro
    defaults: { _controller: ReporteBundle:Reporte:ReporteSeguroVida }

reporte_solicitudempleo:
    pattern:  /reportesolicitud
    defaults: { _controller: ReporteBundle:Reporte:ReporteSolicitud }

reporte_pruebapsicologica:
    pattern:  /reportepruebapsicologica
    defaults: { _controller: ReporteBundle:Reporte:ReportePruebaPsicologica }

reporte_acciones:
    pattern:  /reporteacciones
    defaults: { _controller: ReporteBundle:Reporte:ReporteAcciones }

reporte_hojaservicio:
    pattern:  /reporte_hojaservicio
    defaults: { _controller: ReporteBundle:Reporte:ReporteHojaServicio }

reporte_licencias:
    pattern:  /reporte_licencias
    defaults: { _controller: ReporteBundle:Reporte:ReporteLicencias }

reporte_cartelconcurso:
    pattern:  /reporte_concurso
    defaults: { _controller: ReporteBundle:Reporte:concursoInterno }

reporte_memoconcurso:
    pattern:  /reporte_memoconcurso
    defaults: { _controller: ReporteBundle:Reporte:memoConcurso }

reporte_memocierre_concurso:
    pattern:  /reporte_memocierre
    defaults: { _controller: ReporteBundle:Reporte:memoCierre }

reporte_actacierre_concurso:
    pattern:  /actacierre
    defaults: { _controller: ReporteBundle:Reporte:ActaCierre }

reporte_certificacion:
    pattern:  /reporte_certificacion
    defaults: { _controller: ReporteBundle:Reporte:ReporteCertificacion }

reporte_memorandum:
    pattern:  /memorandum
    defaults: { _controller: ReporteBundle:Reporte:generarMemorandum }

reporte_cartatrabajo:
    pattern:  /cartatrabajo
    defaults: { _controller: ReporteBundle:Reporte:cartaTrabajo }

