reporte_segurovida:
    pattern:  /reporteseguro
    defaults: { _controller: ReporteBundle:Reporte:ReporteSeguroVida }

reporte_solicitudempleo:
    pattern:  /reportesolicitud
    defaults: { _controller: ReporteBundle:Reporte:ReporteSolicitud }

reporte_pruebapsicologica:
    pattern:  /reportepruebapsicologica
    defaults: { _controller: ReporteBundle:Reporte:ReportePruebaPsicologica }

reporte_acciones:
    pattern:  /reporteacciones
    defaults: { _controller: ReporteBundle:Reporte:ReporteAcciones }

reporte_hojaservicio:
    pattern:  /reporte_hojaservicio
    defaults: { _controller: ReporteBundle:Reporte:ReporteHojaServicio }

reporte_licencias:
    pattern:  /reporte_licencias
    defaults: { _controller: ReporteBundle:Reporte:ReporteLicencias }

reporte_cartelconcurso:
    pattern:  /reporte_concurso
    defaults: { _controller: ReporteBundle:Reporte:concursoInterno }

reporte_memoconcurso:
    pattern:  /reporte_memoconcurso
    defaults: { _controller: ReporteBundle:Reporte:memoConcurso }

reporte_memocierre_concurso:
    pattern:  /reporte_memocierre
    defaults: { _controller: ReporteBundle:Reporte:memoCierre }

reporte_actacierre_concurso:
    pattern:  /actacierre
    defaults: { _controller: ReporteBundle:Reporte:ActaCierre }

reporte_certificacion:
    pattern:  /reporte_certificacion
    defaults: { _controller: ReporteBundle:Reporte:ReporteCertificacion }

reporte_memorandum:
    pattern:  /memorandum
    defaults: { _controller: ReporteBundle:Reporte:generarMemorandum }

reporte_cartatrabajo:
    pattern:  /cartatrabajo
    defaults: { _controller: ReporteBundle:Reporte:cartaTrabajo }

reporte_aspirante_plaza:
    pattern:  /plazaaspirante
    defaults: { _controller: ReporteBundle:ModuloReporte:plazaAspirante }

reporte_aspirante_seleccionar:
    pattern:  /seleccionartipo
    defaults: { _controller: ReporteBundle:ModuloReporte:seleccionarReporte }

reporte_aspirante:
    pattern:  /reporteaspirante
    defaults: { _controller: ReporteBundle:ModuloReporte:ReporteAspirante }

reporte_evaluacion:
    pattern:  /reporteevaluacion
    defaults: { _controller: ReporteBundle:Reporte:ReporteEvaluacion }

reporte_empleado_seleccionar:
    pattern:  /seleccionarreporte
    defaults: { _controller: ReporteBundle:ModuloReporte:seleccionarReporteEmpleado }

reporte_empleado_antiguedad:
    pattern:  /reporteantiguedad
    defaults: { _controller: ReporteBundle:ModuloReporte:ReporteEmpleadosAntiguedad }

reporte_empleado_dobleplaza:
    pattern:  /reportedobleplaza
    defaults: { _controller: ReporteBundle:ModuloReporte:ReporteEmpleadosDoblePlaza }

reporte_empleado_centro:
    pattern:  /reporteporcentro
    defaults: { _controller: ReporteBundle:ModuloReporte:ReporteEmpleadosCentro }

reporte_plan_capacitacion:
    pattern:  /reporteplancapacitacion
    defaults: { _controller: ReporteBundle:Reporte:ReportePlanCapacitacion }

reporte_primera_evaluacion:
    pattern:  /reporteevaluacionI
    defaults: { _controller: ReporteBundle:ModuloReporte:PrimeraEvaluacion }

reporte_evaluaciones:
    pattern:  /reporteevaluaciones
    defaults: { _controller: ReporteBundle:ModuloReporte:ReporteEvaluaciones }

reporte_empleado_evaluacion:
    pattern:  /reporteevaluacionesempleados
    defaults: { _controller: ReporteBundle:ModuloReporte:ReporteEmpleadoEvaluacion }

reporte_manualdepuestos:
    pattern:  /manualdepuestospdf
    defaults: { _controller: ReporteBundle:Reporte:ReporteManualdePuestos }

reporte_formularioevaluacion:
    pattern:  /reporte_formularioevaluacion
    defaults: { _controller: ReporteBundle:Reporte:ReporteFormularioEvaluacion }

reporte_otrasacciones:
    pattern:  /reporte_otrasacciones
    defaults: { _controller: ReporteBundle:Reporte:ReporteOtrasAcciones }

consultar_plan:
    pattern:  /consultar_plancapacitacion
    defaults: { _controller: ReporteBundle:ModuloReporte:planConsultar }

reporte_plancapacitacion:
    pattern:  /reporte_plancapacitacion
    defaults: { _controller: ReporteBundle:Reporte:ReporteResultadosPlan }
