reporte_segurovida:
    pattern:  /reporteseguro
    defaults: { _controller: ReporteBundle:Reporte:ReporteSeguroVida }

reporte_solicitudempleo:
    pattern:  /reportesolicitud
    defaults: { _controller: ReporteBundle:Reporte:ReporteSolicitud }

reporte_pruebapsicologica:
    pattern:  /reportepruebapsicologica
    defaults: { _controller: ReporteBundle:Reporte:ReportePruebaPsicologica }

reporte_acciones:
    pattern:  /reporteacciones
    defaults: { _controller: ReporteBundle:Reporte:ReporteAcciones }

reporte_hojaservicio:
    pattern:  /reporte_hojaservicio
    defaults: { _controller: ReporteBundle:Reporte:ReporteHojaServicio }

reporte_licencias:
    pattern:  /reporte_licencias
    defaults: { _controller: ReporteBundle:Reporte:ReporteLicencias }

reporte_certificacion:
    pattern:  /reporte_certificacion
    defaults: { _controller: ReporteBundle:Reporte:ReporteCertificacion }