capacitacionmodificada:
    pattern:  /
    defaults: { _controller: "CapacitacionBundle:Capacitacionmodificada:index" }

capacitacionmodificada_show:
    pattern:  /{id}/show
    defaults: { _controller: "CapacitacionBundle:Capacitacionmodificada:show" }

capacitacionmodificada_new:
    pattern:  /new
    defaults: { _controller: "CapacitacionBundle:Capacitacionmodificada:new" }

capacitacionmodificada_create:
    pattern:  /create
    defaults: { _controller: "CapacitacionBundle:Capacitacionmodificada:create" }
    requirements: { _method: post }

capacitacionmodificada_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "CapacitacionBundle:Capacitacionmodificada:edit" }

capacitacionmodificada_update:
    pattern:  /{id}/update
    defaults: { _controller: "CapacitacionBundle:Capacitacionmodificada:update" }
    requirements: { _method: post|put }

capacitacionmodificada_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "CapacitacionBundle:Capacitacionmodificada:delete" }
    requirements: { _method: post|delete }
