<?php

namespace SIGESRHI\CapacitacionBundle\Repositorio;

use Doctrine\ORM\EntityRepository;

/**
 * PlancapacitacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlancapacitacionRepository extends EntityRepository
{

  /**
   * Descripción: Función utilizada para comprobar si ya existe un plan registrado para el año seleccionado 
   * Retorno:     Cantidad de coincidencias con año enviado
   * Author:      Roquet  
   */
	public function comprobarAnyo($anyo)
    {
        $query = $this->getEntityManager()
                      ->createQuery("SELECT COUNT(p.id) AS plan 
                                     FROM CapacitacionBundle:Plancapacitacion p 
                                     WHERE p.anoplan = :actual AND p.tipoplan = :tipo")
                      ->setParameter('actual', $anyo)
                      ->setParameter('tipo', 'I');

        $resultado = $query->getsingleResult();
        return $resultado['plan'];
    }

  public function comprobarAnyoCentro($anyo,$centro)
    {
        $query = $this->getEntityManager()
                      ->createQuery("SELECT COUNT(p.id) AS plan 
                                     FROM CapacitacionBundle:Plancapacitacion p 
                                     JOIN p.idcentro c
                                     WHERE p.anoplan = :actual and c.id= :centro AND p.tipoplan = :tipo")
                      ->setParameter('actual', $anyo)
                      ->setParameter('centro', $centro)
                      ->setParameter('tipo', 'C');

        $resultado = $query->getsingleResult();
        return $resultado['plan'];
    }

}