capacitacion_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: CapacitacionBundle:Default:index }

CapacitacionBundle_institucion:
    resource: "@CapacitacionBundle/Resources/config/routing/institucioncapacitadora.yml"
    prefix:   /institucion

CapacitacionBundle_capacitador:
    resource: "@CapacitacionBundle/Resources/config/routing/capacitador.yml"
    prefix:   /capacitador

CapacitacionBundle_plancapacitacion:
    resource: "@CapacitacionBundle/Resources/config/routing/plancapacitacion.yml"
    prefix:   /plancapacitacion

CapacitacionBundle_capacitacion:
    resource: "@CapacitacionBundle/Resources/config/routing/capacitacion.yml"
    prefix:   /capacitacion


