parameters:
#    capacitacion.example.class: SIGESRHI\CapacitacionBundle\Example

services:
#    capacitacion.example:
#        class: %capacitacion.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
